language: java
services:
  - mysql
jdk:
  - oraclejdk11
before_install:
  - chmod +x mvnw
install:
  - ./mvnw install -Dspring.profiles.active=prod -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - mysql -e "CREATE DATABASE req_system;" -u root
script:
  - ./mvnw test -Dspring.profiles.active=prod
after_script:
  - docker images
branches:
  only:
    - master