language: java
services:
  - mysql
jdk:
  - oraclejdk11
before_install:
  - chmod +x mvnw
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
install:
  - ./mvnw install -Dspring.profiles.active=test -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - mysql -e "CREATE DATABASE req_system;" -u root
script:
  - ./mvnw test -Dspring.profiles.active=test
after_script:
  - docker images
deploy:
  skip_cleanup: true
  provider: script
  script:
    docker images;
    docker tag org.toft.recsystem/recsystem:0.0.1-SNAPSHOT registry.heroku.com/$HEROKU_APP_NAME/web;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    export WEB_DOCKER_IMAGE_ID=`docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}}`;
    chmod a+x ./release.sh;
    ./release.sh;
branches:
  only:
    - master